<?php
use Magento\Framework\View\Element\Template;
?>
<ul>
    <li>Task 1</li>
    <li>Task 2</li>
    <li>Task 3</li>
</ul>
<div data-bind="scope: 'todo'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "todo": {
                        "component": "MageMastery_Todo/js/view/todo",
                        "template": "MageMastery_Todo/todo",
                        "tasks": [
                            {"label": "task 1"},
                            {"label": "task 2"},
                            {"label": "task 3"}
                        ]
                    }
                }
            }
        }
    }
</script>
